"""Shared constants for the Seestar GUI."""

FITS_SUFFIXES = (".fit", ".fits")
LIGHT_FRAME_EXPANSION_FACTOR = 3.0
LIGHT_PREPROCESS_SEQUENCE_COPIES = 2.0
STACKED_STAGE_ARTIFACT_COPIES = 12.0
LINEAR_RESUME_STAGE_ARTIFACT_COPIES = 8.0
DISK_SPACE_HEADROOM_RATIO = 0.15
DISK_SPACE_MIN_HEADROOM_BYTES = 1 * 1024 * 1024 * 1024
